definitions:
  models.City:
    description: City information with city id and city name
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  models.ErrorResponse:
    description: Information about error
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/cities:
    get:
      description: Get all cities
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.City'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
      summary: Get all cities
      tags:
      - Cities
  /api/v1/cities/{id}:
    get:
      description: Get city by ID
      parameters:
      - description: City ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.City'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
      summary: Get city by ID
      tags:
      - Cities
swagger: "2.0"
